"""Export a Gaia star field for the browser scene.

Phase 2's sky is procedural — random points that look like stars and are not. This
replaces it with the real thing: actual Gaia sources at their measured directions,
brightnesses and colours, so the constellations in the scene are the constellations.

Two views come out of the same rows:

* **from Earth** — the direction and apparent magnitude of each star, which is the
  sky as seen from inside the solar system;
* **from outside** — the same stars at their measured 3D positions in parsecs, which
  is what "zoom out to the galaxy" actually means.

Both are packed into one compact JSON. Size matters here in a way it did not for the
element table: this ships to a browser. So values are rounded to the precision the
renderer can actually use — four decimals on a unit vector is about a twentieth of an
arcminute, far finer than a pixel — and the star count is capped.

Usage::

    python scripts/export_star_data.py
    python scripts/export_star_data.py --count 12000

Writes ``web/src/data/stars.generated.json``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from orrery.gaia import (
    bp_rp_to_rgb,
    equatorial_to_cartesian,
    icrs_to_galactic_matrix,
    load_gaia_sample,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "web" / "src" / "data" / "stars.generated.json"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--count", type=int, default=9000, help="how many of the brightest stars to export"
    )
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()

    try:
        catalogue = load_gaia_sample()
    except FileNotFoundError as error:
        raise SystemExit(str(error)) from error

    stars = catalogue.brightest(args.count)

    # Direction as seen from the solar system, in the equatorial frame the scene
    # already knows how to rotate into the ecliptic.
    direction = equatorial_to_cartesian(stars.ra, stars.dec)

    distance = stars.distance_parsec()
    galactic = np.einsum("ij,nj->ni", icrs_to_galactic_matrix(), direction) * distance[:, None]

    colours = bp_rp_to_rgb(stars.bp_rp)
    usable = np.isfinite(distance)

    # Colour index and absolute magnitude are the two axes of the Hertzsprung-Russell
    # diagram, so shipping them lets the browser draw it and link a selection there
    # back to the stars in 3D. Absolute magnitude needs a distance, so it is null
    # wherever the parallax was too noisy to invert.
    absolute = stars.absolute_g()

    payload = {
        "_comment": (
            "GENERATED by scripts/export_star_data.py from a Gaia DR3 snapshot. "
            "Do not edit by hand. 'direction' is a unit vector in equatorial J2000; "
            "'magnitude' is apparent Gaia G; 'colour' is an approximate display RGB; "
            "'galactic' is the 3D position in parsecs with the Sun at the origin; "
            "'bpRp' and 'absoluteG' are the Hertzsprung-Russell axes. The last three "
            "are null where the parallax was too noisy to invert."
        ),
        "count": len(stars),
        "magnitudeRange": [
            round(float(stars.g_magnitude.min()), 3),
            round(float(stars.g_magnitude.max()), 3),
        ],
        "withDistance": int(usable.sum()),
        "direction": [[round(float(v), 4) for v in row] for row in direction],
        "magnitude": [round(float(m), 2) for m in stars.g_magnitude],
        "colour": [[round(float(c), 3) for c in row] for row in colours],
        "galactic": [
            [round(float(v), 2) for v in row] if ok else None
            for row, ok in zip(galactic, usable, strict=True)
        ],
        "bpRp": [round(float(c), 3) if np.isfinite(c) else None for c in stars.bp_rp],
        "absoluteG": [
            round(float(m), 3) if np.isfinite(m) else None for m in absolute
        ],
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, separators=(",", ":")) + "\n", encoding="utf-8")

    size_kb = args.output.stat().st_size / 1024
    print(f"wrote {args.output.relative_to(REPO_ROOT)}  ({size_kb:.0f} kB)")
    print(f"  stars:            {len(stars):,}")
    print(f"  magnitude range:  {payload['magnitudeRange'][0]} to {payload['magnitudeRange'][1]}")
    print(f"  with a distance:  {payload['withDistance']:,}")
    print(f"  naked-eye (G<6):  {int((stars.g_magnitude < 6.0).sum()):,}")
    print(f"  on the HR diagram: {int(np.isfinite(absolute).sum()):,}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
