"""Train and evaluate the phase 5 models, then render the figure.

Four panels:

(a) **The physics.** Survival rate against Hill separation, with Gladman's analytic
    threshold and the best fitted threshold marked. This is what the model is trying
    to learn, drawn straight from the simulations.
(b) **Did the model earn its place?** ROC curves for the learned model and for the
    single best cut on Hill separation, with Gladman's fixed rule as a point. Beating
    the tuned threshold is the claim that means something.
(c) **What the model used.** Permutation importance on held-out data.
(d) **The leakage trap.** The same KOI classifier with and without the vetting flags.
    The near-perfect curve is the worthless one.

The stability dataset is generated by simulating every system, which takes a couple
of minutes. The KOI panel needs a snapshot::

    python scripts/fetch_exoplanets.py --koi

Usage::

    python scripts/train_models.py
    python scripts/train_models.py --quick    # smaller sample, for iterating

Writes ``docs/images/phase5-models-light.png`` and ``-dark.png``.
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from sklearn.metrics import roc_curve  # noqa: E402

from orrery.koi import load_koi_table  # noqa: E402
from orrery.models import evaluate_koi_leakage, evaluate_stability_models  # noqa: E402
from orrery.stability import (  # noqa: E402
    HILL_STABILITY_THRESHOLD,
    build_stability_dataset,
)

THEMES = {
    "light": {
        "surface": "#fcfcfb",
        "page": "#f9f9f7",
        "ink": "#0b0b0b",
        "ink_secondary": "#52514e",
        "ink_muted": "#898781",
        "grid": "#e1e0d9",
        "axis": "#c3c2b7",
        "series": ("#2a78d6", "#eb6834", "#1baf7a"),
    },
    "dark": {
        "surface": "#1a1a19",
        "page": "#0d0d0d",
        "ink": "#ffffff",
        "ink_secondary": "#c3c2b7",
        "ink_muted": "#898781",
        "grid": "#2c2c2a",
        "axis": "#383835",
        "series": ("#3987e5", "#d95926", "#199e70"),
    },
}

MARKER_SIZE = 7.0
LINE_WIDTH = 1.8


def style_axes(ax, theme: dict) -> None:
    ax.set_facecolor(theme["surface"])
    ax.grid(True, color=theme["grid"], linewidth=0.6, zorder=0)
    ax.tick_params(colors=theme["ink_muted"], labelsize=8, length=3, width=0.6)
    for spine in ax.spines.values():
        spine.set_color(theme["axis"])
        spine.set_linewidth(0.8)


def plot_physics(ax, theme, dataset, tuned_threshold) -> None:
    """Survival rate against separation: the boundary the model has to find."""
    style_axes(ax, theme)
    ax.set_title(
        "(a) What the simulations say", color=theme["ink"], fontsize=10, pad=10, loc="left"
    )
    ax.set_xlabel("orbital separation Δ (mutual Hill radii)", color=theme["ink_muted"], fontsize=8)
    ax.set_ylabel("fraction still stable", color=theme["ink_muted"], fontsize=8)

    edges = np.linspace(dataset.hill_separation.min(), dataset.hill_separation.max(), 22)
    centres, rates, counts = [], [], []
    for low, high in zip(edges[:-1], edges[1:], strict=True):
        mask = (dataset.hill_separation >= low) & (dataset.hill_separation < high)
        if mask.sum() >= 5:
            centres.append(0.5 * (low + high))
            rates.append(dataset.labels[mask].mean())
            counts.append(mask.sum())

    centres, rates, counts = np.array(centres), np.array(rates), np.array(counts)
    # Binomial standard error: bins with few systems deserve visible uncertainty.
    errors = np.sqrt(rates * (1 - rates) / counts)

    ax.errorbar(
        centres, rates, yerr=errors, color=theme["series"][0], linewidth=LINE_WIDTH,
        marker="o", markersize=MARKER_SIZE - 2, markeredgecolor=theme["surface"],
        markeredgewidth=1.2, capsize=2.5, elinewidth=0.9, zorder=3,
    )

    # Short rotated labels only — the numbers go in the note below, because a rotated
    # string long enough to carry them runs off the top of the axes.
    for value, label, style, height in (
        (HILL_STABILITY_THRESHOLD, "Gladman", "-", 0.30),
        (tuned_threshold, "best cut", (0, (5, 4)), 0.30),
    ):
        ax.axvline(value, color=theme["ink_secondary"], linewidth=1.2, linestyle=style, zorder=2)
        ax.annotate(
            label, (value, height), textcoords="offset points", xytext=(-13, 0),
            fontsize=7.5, color=theme["ink_secondary"], rotation=90, va="bottom",
        )

    ax.set_ylim(-0.03, 1.06)
    ax.text(
        0.97, 0.32,
        f"{len(dataset):,} systems, each integrated\n"
        f"for {dataset.orbits_simulated:.0f} inner orbits.\n"
        "Error bars are binomial.\n\n"
        f"Gladman  Δ = {HILL_STABILITY_THRESHOLD:.2f}\n"
        f"best cut  Δ = {tuned_threshold:.2f}",
        transform=ax.transAxes, fontsize=7.5, color=theme["ink_muted"],
        ha="right", va="top",
    )


def plot_roc(ax, theme, comparison) -> None:
    """ROC curves, plus Gladman as the single point a fixed rule produces."""
    style_axes(ax, theme)
    ax.set_title(
        "(b) Did the model earn its place?", color=theme["ink"], fontsize=10, pad=10, loc="left"
    )
    ax.set_xlabel("false positive rate", color=theme["ink_muted"], fontsize=8)
    ax.set_ylabel("true positive rate", color=theme["ink_muted"], fontsize=8)

    labels = comparison.test_labels

    # Anchored at different fractions along each curve: the two run close together by
    # construction, so a shared anchor point would overprint the labels.
    for scores, key, name, colour, fraction, offset in (
        (
            comparison.test_hill_separation, "Tuned threshold", "Threshold on Δ alone",
            theme["series"][1], 0.55, (10, -22),
        ),
        (
            comparison.model_probabilities, "Gradient boosting", "Gradient boosting",
            theme["series"][0], 0.18, (12, -6),
        ),
    ):
        false_rate, true_rate, _ = roc_curve(labels, scores)
        auc = comparison.by_name(key).roc_auc
        ax.plot(false_rate, true_rate, color=colour, linewidth=LINE_WIDTH, zorder=3)

        anchor = int(fraction * (len(false_rate) - 1))
        ax.annotate(
            f"{name}\nAUC {auc:.3f}",
            (false_rate[anchor], true_rate[anchor]),
            textcoords="offset points", xytext=offset, fontsize=7.5,
            color=theme["ink_secondary"],
        )

    gladman = comparison.by_name("Gladman criterion")
    predicted = gladman.predictions
    true_positive = np.sum((predicted == 1) & (labels == 1)) / np.sum(labels == 1)
    false_positive = np.sum((predicted == 1) & (labels == 0)) / np.sum(labels == 0)

    ax.plot(
        false_positive, true_positive, marker="D", markersize=MARKER_SIZE + 1,
        color=theme["ink"], markeredgecolor=theme["surface"], markeredgewidth=1.4, zorder=5,
    )
    ax.annotate(
        "Gladman criterion\n(a fixed rule has no curve)",
        (false_positive, true_positive), textcoords="offset points", xytext=(10, -4),
        fontsize=7.5, color=theme["ink"],
    )

    ax.plot(
        [0, 1], [0, 1], color=theme["ink_muted"], linewidth=0.9,
        linestyle=(0, (4, 4)), zorder=1,
    )
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.02)

    accuracies = "   ".join(
        f"{score.name.split()[0]} {score.accuracy:.3f}" for score in comparison.scores
    )
    ax.text(
        0.5, -0.19, f"held-out accuracy:   {accuracies}",
        transform=ax.transAxes, fontsize=7.5, color=theme["ink_muted"], ha="center", va="top",
    )


def plot_importance(ax, theme, comparison) -> None:
    """Permutation importance, measured on data the model never saw."""
    style_axes(ax, theme)
    ax.grid(False, axis="y")
    ax.set_title(
        "(c) What the model actually used", color=theme["ink"], fontsize=10, pad=10, loc="left"
    )
    ax.set_xlabel("drop in held-out AUC when shuffled", color=theme["ink_muted"], fontsize=8)

    items = [(name, value) for name, value in comparison.feature_importance.items()][:7]
    positions = np.arange(len(items))[::-1]

    for (_, value), y in zip(items, positions, strict=True):
        ax.plot([0, max(value, 0)], [y, y], color=theme["series"][0], linewidth=1.4, zorder=2)
        ax.plot(
            max(value, 0), y, marker="o", markersize=MARKER_SIZE, color=theme["series"][0],
            markeredgecolor=theme["surface"], markeredgewidth=1.4, zorder=4,
        )
        ax.annotate(
            f"{value:.3f}", (max(value, 0), y), textcoords="offset points",
            xytext=(10, -3), fontsize=7.5, color=theme["ink_secondary"],
        )

    ax.set_yticks(positions)
    ax.set_yticklabels(
        [name.replace("_", " ") for name, _ in items], fontsize=8, color=theme["ink_secondary"]
    )
    left, right = ax.get_xlim()
    ax.set_xlim(-0.005, right * 1.25)

    ax.text(
        0.5, -0.19,
        "Separation dominates, as the physics says it should — but eccentricity contributes,\n"
        "and that is information Gladman's circular-orbit derivation structurally cannot use.",
        transform=ax.transAxes, fontsize=7.5, color=theme["ink_muted"], ha="center", va="top",
    )


def plot_leakage(ax, theme, leakage) -> None:
    """The same classifier with and without the answer key."""
    style_axes(ax, theme)
    ax.set_title(
        "(d) The leakage trap, on real Kepler data",
        color=theme["ink"], fontsize=10, pad=10, loc="left",
    )
    ax.set_xlabel("false positive rate", color=theme["ink_muted"], fontsize=8)
    ax.set_ylabel("true positive rate", color=theme["ink_muted"], fontsize=8)

    if leakage is None:
        ax.text(
            0.5, 0.5,
            "No KOI snapshot found.\n\nRun:  python scripts/fetch_exoplanets.py --koi",
            transform=ax.transAxes, fontsize=9, color=theme["ink_muted"],
            ha="center", va="center",
        )
        return

    truth = leakage.test_labels

    # Curves are drawn from the predicted *probabilities*, not the thresholded
    # labels: a ROC of hard 0/1 predictions collapses to three points and would make
    # both models look far worse than they are.
    # Labels positioned in axes fractions, not anchored to the curves. Both ROCs hug
    # the top-left corner, so a curve-relative anchor puts the text off the axes and
    # into the panel title.
    for score, colour, note, position in (
        (leakage.physical, theme["series"][0], "honest", (0.30, 0.62)),
        (leakage.with_leakage, theme["series"][1], "worthless", (0.30, 0.86)),
    ):
        false_rate, true_rate, _ = roc_curve(truth, score.scores)
        ax.plot(false_rate, true_rate, color=colour, linewidth=LINE_WIDTH, zorder=3)

        ax.text(
            *position,
            f"{score.name}\nacc {score.accuracy:.4f} · AUC {score.roc_auc:.4f}  ({note})",
            transform=ax.transAxes, fontsize=7.5, color=theme["ink_secondary"],
        )

    ax.plot(
        [0, 1], [0, 1], color=theme["ink_muted"], linewidth=0.9,
        linestyle=(0, (4, 4)), zorder=1,
    )
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.02)

    worst = max(leakage.leaky_importance.items(), key=lambda item: item[1])
    ax.text(
        0.5, -0.19,
        f"The vetting flags buy {leakage.accuracy_gap:+.1%} accuracy and are worth nothing:\n"
        "they encode the reason a signal was rejected.\n"
        f"Most influential: {worst[0]} (+{worst[1]:.3f} AUC).",
        transform=ax.transAxes, fontsize=7.5, color=theme["ink_muted"], ha="center", va="top",
    )


def build_figure(mode, dataset, comparison, leakage, tuned_threshold, output: Path) -> None:
    theme = THEMES[mode]

    figure, axes = plt.subplots(2, 2, figsize=(13.6, 11.6), facecolor=theme["page"])
    figure.suptitle(
        "orrery-lab · phase 5 · two models, and the baselines that keep them honest",
        color=theme["ink"], fontsize=13, x=0.045, ha="left", y=0.975,
    )
    figure.text(
        0.045, 0.944,
        "The stability labels are generated by this project's own N-body integrator, "
        "not downloaded.",
        color=theme["ink_muted"], fontsize=9, ha="left",
    )

    plot_physics(axes[0][0], theme, dataset, tuned_threshold)
    plot_roc(axes[0][1], theme, comparison)
    plot_importance(axes[1][0], theme, comparison)
    plot_leakage(axes[1][1], theme, leakage)

    figure.tight_layout(rect=(0.0, 0.0, 1.0, 0.93), h_pad=3.8)
    output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output, dpi=170, facecolor=theme["page"])
    plt.close(figure)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quick", action="store_true", help="smaller sample, for iterating")
    parser.add_argument("--outdir", default="docs/images")
    args = parser.parse_args()

    count = 800 if args.quick else 2500
    orbits = 300.0 if args.quick else 1200.0

    started = time.perf_counter()
    print(f"Simulating {count:,} two-planet systems for {orbits:.0f} inner orbits ...")
    dataset = build_stability_dataset(count=count, orbits=orbits)
    print(
        f"  {time.perf_counter() - started:.0f} s — {dataset.stable_fraction:.1%} stable, "
        f"{1 - dataset.stable_fraction:.1%} disrupted"
    )

    comparison = evaluate_stability_models(dataset)
    tuned = comparison.by_name("Tuned threshold")
    tuned_threshold = float(tuned.detail.split(">")[1].split(",")[0])

    print("\nStability, held-out test split:")
    for score in comparison.scores:
        auc = f"{score.roc_auc:.4f}" if score.roc_auc == score.roc_auc else "   —  "
        print(f"  {score.name:<20} accuracy {score.accuracy:.4f}   AUC {auc}   {score.detail}")
    mean, deviation = comparison.cross_validated_auc
    print(f"  5-fold cross-validated AUC: {mean:.4f} ± {deviation:.4f}")

    print("\n  permutation importance (held-out AUC):")
    for name, value in list(comparison.feature_importance.items())[:6]:
        print(f"    {name:<24} {value:+.4f}")

    try:
        leakage = evaluate_koi_leakage(load_koi_table())
        print(f"\nKOI classification, {leakage.sample_size:,} complete rows:")
        print(
            f"  {leakage.physical.name:<28} accuracy {leakage.physical.accuracy:.4f}   "
            f"AUC {leakage.physical.roc_auc:.4f}"
        )
        print(
            f"  {leakage.with_leakage.name:<28} accuracy {leakage.with_leakage.accuracy:.4f}   "
            f"AUC {leakage.with_leakage.roc_auc:.4f}"
        )
        print(f"  leakage buys {leakage.accuracy_gap:+.2%} accuracy and means nothing")
        print("\n  leaked-column importance:")
        for name, value in leakage.leaky_importance.items():
            print(f"    {name:<20} {value:+.4f}")
    except FileNotFoundError:
        leakage = None
        print("\nNo KOI snapshot; panel (d) will say so.")

    outdir = Path(args.outdir)
    for mode in ("light", "dark"):
        target = outdir / f"phase5-models-{mode}.png"
        build_figure(mode, dataset, comparison, leakage, tuned_threshold, target)
        print(f"\nwrote {target}")

    print(f"\ntotal {time.perf_counter() - started:.0f} s")


if __name__ == "__main__":
    main()
